[NO-TICKET] Refactoring
veryfi/veryfi-nodejs pull request #31
Opened 2023-07-21 21:09 UTC by vekaev

2023-09-08 02:11 UTC, alejouribesanchez requested changes
Add .DS_STORE files to gitignore

2023-09-08 02:11 UTC, alejouribesanchez commented on .DS_Store
Add this file to the .gitignore

2023-09-08 02:11 UTC, alejouribesanchez commented on docs/.DS_Store
Add this file to gitignore

2023-10-21 21:50 UTC, vekaev commented
lol)

2023-11-07 13:29 UTC, closed without merging

2023-11-07 13:29 UTC, alejouribesanchez commented
Conflicts